apiVersion: v1
kind: ConfigMap
metadata:
  namespace: udaconnect
  name: db-env
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: udaconnect
  name: kafka-env
data:
  KAFKA_TOPIC: "locations"
  KAFKA_HOST: "kafka-broker-0.kafka-broker-headless.udaconnect.svc.cluster.local:9092"