apiVersion: v1
kind: Service
metadata:
  namespace: udaconnect
  name: locations
  labels:
    service: locations
spec:
  ports:
  - port: 5000
    #targetPort: 5000
    nodePort: 30002
  selector:
    app: locations-api
    ver: v1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: udaconnect
  labels:
    app: locations-api
  name: locations-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations-api
  template:
    metadata:
      labels:
        log: services
        app: locations-api
        ver: v1
    spec:
      containers:
      - image: pufe97/locations-api:latest
        name: locations-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
