apiVersion: v1
kind: Service
metadata:
  namespace: udaconnect
  name: persons-svc-api
  labels:
    service: persons-svc-api
spec:
  ports:
  - name: "flask-5000"
    port: 5000
    targetPort: 5000
    nodePort: 30006
  selector:
    app: persons-app-api
    ver: v1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: udaconnect
  labels:
    app: persons-app-api
  name: persons-app-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: persons-app-api
  template:
    metadata:
      labels:
        app: persons-app-api
        ver: v1
    spec:
      containers:
      - image: pufe97/persons-app-api:latest
        name: persons-app-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
